export const fsExtraMethods = [
	'copy'
,	'createOutputStream'
,	'emptyDir'
,	'ensureFile'
,	'ensureDir'
,	'ensureLink'
,	'ensureSymlink'
,	'mkdirs'
,	'move'
,	'outputJson'
,	'readJson'
,	'remove'
,	'writeJson'
]