export const fsMethodsSync = [
	'renameSync'
,	'ftruncateSync'
,	'truncateSync'
,	'chownSync'
,	'fchownSync'
,	'lchownSync'
,	'chmodSync'
,	'fchmodSync'
,	'lchmodSync'
,	'statSync'
,	'lstatSync'
,	'fstatSync'
,	'linkSync'
,	'symlinkSync'
,	'readlinkSync'
,	'realpathSync'
,	'unlinkSync'
,	'rmdirSync'
,	'mkdirSync'
,	'readdirSync'
,	'closeSync'
,	'openSync'
,	'utimesSync'
,	'futimesSync'
,	'fsyncSync'
,	'writeSync'
,	'readSync'
,	'readFileSync'
,	'writeFileSync'
,	'appendFileSync'
,	'existsSync'
,	'accessSync'
,	'F_OK'
,	'R_OK'
,	'W_OK'
,	'X_OK'
]